# sistema_pyme/database.pyi
import sqlite3
from typing import Optional, Dict, Any, List

def init_db() -> sqlite3.Connection: ...

def save_business(conn: sqlite3.Connection, name: str, business_type: str, description: Optional[str] = None) -> None: ...

def get_current_business(conn: sqlite3.Connection) -> Optional[Dict[str, Any]]: ...

def log_event(conn: sqlite3.Connection, event_type: str, event_data: Any, user_id: Optional[int] = None) -> int: ...

def get_recent_events(conn: sqlite3.Connection, limit: int = 50) -> List[Any]: ...

def create_notification(conn: sqlite3.Connection, notif_type: str, title: str, message: str, priority: str = "medium", user_id: Optional[int] = None) -> int: ...

def get_user_notifications(conn: sqlite3.Connection, user_id: int, unread_only: bool = True) -> List[Any]: ...

def mark_notification_as_read(conn: sqlite3.Connection, notification_id: int, user_id: int) -> bool: ...